Repository nhsengland/datascience, pull requests merged in 2024-05, with the labels that each got.

#111 HS consistent capitalisation of role titles
  docs/PhDInterns.md
  docs/about.md
  docs/useful_links.md
  docs/what_is_data_science/Benefits of Data Science in the NHS.md
  docs/what_is_data_science/How you can learn Data Science.md
  docs/what_is_data_science/index.md
Labels: documentation, good first issue

#108 Dg ae forecasting: A page for the A&E forecasting project
  docs/images/a_and_e_forecasting/comparative_forecast.png
  docs/images/a_and_e_forecasting/forecast.png
  docs/images/a_and_e_forecasting/overview.png
  docs/images/a_and_e_forecasting/weekly_trends.png
  docs/our_work/a_and_e_forecasting_tool.md
  mkdocs.yml
Labels: documentation

#115 MT updating automod repo link to the public version
  docs/our_work/ratings-and-reviews.md
Labels: enhancement
